//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovatian.Configuration.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Innovatian.Configuration.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string EmptySectionnameTest0 {
            get {
                return ResourceManager.GetString("EmptySectionnameTest0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [           ].
        /// </summary>
        internal static string EmptySectionnameTest1 {
            get {
                return ResourceManager.GetString("EmptySectionnameTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [kasdk]
        ///[].
        /// </summary>
        internal static string EmptySectionnameTest2 {
            get {
                return ResourceManager.GetString("EmptySectionnameTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; last modified 1 April 2001 by John Doe
        ///[owner]
        ///name=John Doe
        ///organization=Acme Products
        /// 
        ///[database]
        ///server=192.0.2.42     ; use IP address in case network name resolution is not working
        ///port=143
        ///file = &quot;acme payroll.dat&quot;
        ///
        ///[Empty]
        ///=MyEmptyKey
        ///MyEmptyValue=
        ///=
        ///
        ///[Completely Empty Section]
        ///[  NonEmptyAfterCompletelyEmpty   ]
        ///; adding = after comment;=
        ///   mykey    =  myval  akdk     ;
        ///multi= myvalue=do.
        /// </summary>
        internal static string IniTestCases {
            get {
                return ResourceManager.GetString("IniTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 &lt;PolicyLevel version=&quot;1&quot;&gt;
        ///                    &lt;SecurityClasses&gt;
        ///                        &lt;SecurityClass Name=&quot;AllMembershipCondition&quot; Description=&quot;System.Security.Policy.AllMembershipCondition, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;/&gt;
        ///                        &lt;SecurityClass Name=&quot;AspNetHostingPermission&quot; Description=&quot;System.Web.AspNetHostingPermission, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;/&gt;
        ///                         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MediumTrustConfig {
            get {
                return ResourceManager.GetString("MediumTrustConfig", resourceCulture);
            }
        }
    }
}
